import 'dotenv/config';
import { db } from '@/db';
import { v4 as uuidv4 } from 'uuid';
import {
  user,
  universities,
  courses,
  tutors,
  tutorCourses,
  availabilitySlots,
  bookings,
  bookingEvents,
  payouts,
  reviews,
  conversations,
  messages,
} from '@/db/schema';

// Generate UUIDs for all users
const userIds = {
  emma: uuidv4(),
  ahmed: uuidv4(),
  sofia: uuidv4(),
  lars: uuidv4(),
  priya: uuidv4(),
  marco: uuidv4(),
  fatima: uuidv4(),
  chen: uuidv4(),
  max: uuidv4(),
  sarah: uuidv4(),
  david: uuidv4(),
  lisa: uuidv4(),
  student: '0UiEdkI6pgd7ZMRsiUZLic4E4lI0U1Oe',
};

const universityIds = {
  uva: uuidv4(),
  vu: uuidv4(),
  hva: uuidv4(),
};

const courseIds = {
  linearAlgebra: uuidv4(),
  dataStructures: uuidv4(),
  physics1: uuidv4(),
};

const tutorIds = {
  emma: uuidv4(),
  ahmed: uuidv4(),
  sofia: uuidv4(),
  lars: uuidv4(),
  priya: uuidv4(),
  marco: uuidv4(),
  fatima: uuidv4(),
  chen: uuidv4(),
  chat: '6f2d517e-64a2-4a42-bc0b-74ee2c154373',
};

const bookingIds = {
  booking1: uuidv4(),
  booking2: uuidv4(),
  booking3: uuidv4(),
  booking4: uuidv4(),
  booking5: uuidv4(),
  booking6: uuidv4(),
  booking7: uuidv4(),
  booking8: uuidv4(),
  booking9: uuidv4(),
};

const conversationIds = {
  maxEmma: uuidv4(),
  sarahAhmed: uuidv4(),
  davidSofia: uuidv4(),
  lisaLars: uuidv4(),
  maxPriya: uuidv4(),
  sarahMarco: uuidv4(),
  davidFatima: uuidv4(),
};

async function seeduser() {
  const sampleuser = [
    {
      id: userIds.emma,
      location: 'Amsterdam, Netherlands',
      email: 'emma.vandenberg@student.uva.nl',
      role: 'tutor',
      name: 'Emma van der Berg',
      image: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Emma',
      isActive: true,
      createdAt: new Date('2024-01-15').toISOString(),
      updatedAt: new Date('2024-01-15').toISOString(),
    },
    {
      id: userIds.ahmed,
      location: 'Amsterdam, Netherlands',
      email: 'ahmed.hassan@student.vu.nl',
      role: 'tutor',
      name: 'Ahmed Hassan',
      image: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Ahmed',
      isActive: true,
      createdAt: new Date('2024-01-18').toISOString(),
      updatedAt: new Date('2024-01-18').toISOString(),
    },
    {
      id: userIds.sofia,
      email: 'sofia.rodriguez@student.hva.nl',
      location: 'Amsterdam, Netherlands',
      role: 'tutor',
      name: 'Sofia Rodriguez',
      image: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Sofia',
      isActive: true,
      createdAt: new Date('2024-01-20').toISOString(),
      updatedAt: new Date('2024-01-20').toISOString(),
    },
    {
      id: userIds.lars,
      email: 'lars.nielsen@student.uva.nl',
      location: 'Amsterdam, Netherlands',
      role: 'tutor',
      name: 'Lars Nielsen',
      image: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Lars',
      isActive: true,
      createdAt: new Date('2024-01-22').toISOString(),
      updatedAt: new Date('2024-01-22').toISOString(),
    },
    {
      id: userIds.priya,
      email: 'priya.patel@student.vu.nl',
      location: 'Amsterdam, Netherlands',
      role: 'tutor',
      name: 'Priya Patel',
      image: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Priya',
      isActive: true,
      createdAt: new Date('2024-01-25').toISOString(),
      updatedAt: new Date('2024-01-25').toISOString(),
    },
    {
      id: userIds.marco,
      email: 'marco.rossi@student.hva.nl',
      location: 'Amsterdam, Netherlands',
      role: 'tutor',
      name: 'Marco Rossi',
      image: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Marco',
      isActive: true,
      createdAt: new Date('2024-01-28').toISOString(),
      updatedAt: new Date('2024-01-28').toISOString(),
    },
    {
      id: userIds.fatima,
      email: 'fatima.alzahra@student.abs.nl',
      location: 'Amsterdam, Netherlands',
      role: 'tutor',
      name: 'Fatima Al-Zahra',
      image: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Fatima',
      isActive: true,
      createdAt: new Date('2024-02-01').toISOString(),
      updatedAt: new Date('2024-02-01').toISOString(),
    },
    {
      id: userIds.chen,
      email: 'chen.wei@student.uva.nl',
      location: 'Amsterdam, Netherlands',
      role: 'tutor',
      name: 'Chen Wei',
      image: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Chen',
      isActive: true,
      createdAt: new Date('2024-02-03').toISOString(),
      updatedAt: new Date('2024-02-03').toISOString(),
    },
    {
      id: userIds.max,
      email: 'max.devries@student.uva.nl',
      location: 'Amsterdam, Netherlands',
      role: 'student',
      name: 'Max de Vries',
      image: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Atilla',
      isActive: true,
      createdAt: new Date('2024-02-05').toISOString(),
      updatedAt: new Date('2024-02-05').toISOString(),
    },
    {
      id: userIds.sarah,
      email: 'sarah.johnson@student.vu.nl',
      location: 'Amsterdam, Netherlands',
      role: 'student',
      name: 'Sarah Johnson',
      image: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Fatima',
      isActive: true,
      createdAt: new Date('2024-02-08').toISOString(),
      updatedAt: new Date('2024-02-08').toISOString(),
    },
    {
      id: userIds.david,
      email: 'david.kim@student.hva.nl',
      location: 'Amsterdam, Netherlands',
      role: 'student',
      name: 'David Kim',
      image: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Cagan',
      isActive: true,
      createdAt: new Date('2024-02-10').toISOString(),
      updatedAt: new Date('2024-02-10').toISOString(),
    },
    {
      id: userIds.lisa,
      email: 'lisa.mueller@student.uva.nl',
      location: 'Amsterdam, Netherlands',
      role: 'student',
      name: 'Lisa Mueller',
      image: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Lars',
      isActive: true,
      createdAt: new Date('2024-02-12').toISOString(),
      updatedAt: new Date('2024-02-12').toISOString(),
    }
  ];

  await db.insert(user).values(sampleuser);
  console.log('✅ user seeded');
}

async function seedUniversities() {
  const sampleUniversities = [
    {
      id: universityIds.uva,
      name: 'University of Amsterdam',
      shortName: 'UvA',
      city: 'Amsterdam',
      country: 'Netherlands',
      isActive: true,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      id: universityIds.vu,
      name: 'Vrije Universiteit Amsterdam',
      shortName: 'VU',
      city: 'Amsterdam',
      country: 'Netherlands',
      isActive: true,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      id: universityIds.hva,
      name: 'Hogeschool van Amsterdam',
      shortName: 'HvA',
      city: 'Amsterdam',
      country: 'Netherlands',
      isActive: true,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
  ];

  await db.insert(universities).values(sampleUniversities);
  console.log('✅ Universities seeded');
}

async function seedCourses() {
  const sampleCourses = [
    {
      id: courseIds.linearAlgebra,
      name: 'Linear Algebra',
      code: 'MA101',
      department: 'Mathematics',
      universityId: universityIds.uva,
      description: 'Introduction to linear algebra concepts',
      tags: JSON.stringify(['math', 'linear-algebra', 'algebra']),
      isActive: true,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      id: courseIds.dataStructures,
      name: 'Data Structures',
      code: 'CS201',
      department: 'Computer Science',
      universityId: universityIds.uva,
      description: 'Fundamentals of data structures and algorithms',
      tags: JSON.stringify(['cs', 'algorithms', 'programming']),
      isActive: true,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      id: courseIds.physics1,
      name: 'Physics I',
      code: 'PH101',
      department: 'Physics',
      universityId: universityIds.vu,
      description: 'Classical mechanics and thermodynamics',
      tags: JSON.stringify(['physics', 'mechanics']),
      isActive: true,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
  ];

  await db.insert(courses).values(sampleCourses);
  console.log('✅ Courses seeded');
}

async function seedTutors() {
  const sampleTutors = [
    {
      id: tutorIds.emma,
      location: 'Amsterdam, Netherlands',
      userId: userIds.emma,
      universityId: universityIds.uva,
      image: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Emma',
      bio: 'Mathematics and physics enthusiast with 5+ years of experience',
      hourlyRate: 25,
      languages: JSON.stringify(['English', 'Dutch']),
      courseTags: JSON.stringify(['Linear Algebra', 'Calculus']),
      verified: true,
      isAvailable: true,
      ratingAvg: 4.8,
      reviewCount: 12,
      totalEarnings: 300,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      id: tutorIds.ahmed,
      location: 'Amsterdam, Netherlands',
      userId: userIds.ahmed,
      universityId: universityIds.vu,
      image: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Ahmed',
      bio: 'Computer Science tutor specializing in data structures and algorithms',
      hourlyRate: 30,
      languages: JSON.stringify(['English', 'Arabic']),
      courseTags: JSON.stringify(['Data Structures', 'Algorithms']),
      verified: true,
      isAvailable: true,
      ratingAvg: 4.9,
      reviewCount: 8,
      totalEarnings: 240,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      id: tutorIds.sofia,
      location: 'Amsterdam, Netherlands',
      userId: userIds.sofia,
      universityId: universityIds.hva,
      image: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Sofia',
      bio: 'Physics expert with practical lab experience',
      hourlyRate: 35,
      languages: JSON.stringify(['English', 'Dutch', 'German']),
      courseTags: JSON.stringify(['Physics', 'Mechanics', 'Thermodynamics']),
      verified: true,
      isAvailable: true,
      ratingAvg: 4.7,
      reviewCount: 15,
      totalEarnings: 525,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      id: tutorIds.lars,
      location: 'Amsterdam, Netherlands',
      userId: userIds.lars,
      universityId: universityIds.uva,
      image: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Lars',
      bio: 'Passionate about making complex subjects simple and engaging',
      hourlyRate: 20,
      languages: JSON.stringify(['English', 'Dutch']),
      courseTags: JSON.stringify(['Linear Algebra', 'Physics']),
      verified: false,
      isAvailable: true,
      ratingAvg: 4.3,
      reviewCount: 5,
      totalEarnings: 100,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      id: tutorIds.priya,
      location: 'Amsterdam, Netherlands',
      userId: userIds.priya,
      universityId: universityIds.vu,
      image: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Priya',
      bio: 'Advanced tutor in algorithms and computational complexity',
      hourlyRate: 45,
      languages: JSON.stringify(['English', 'Dutch', 'Spanish']),
      courseTags: JSON.stringify(['Data Structures', 'Algorithms', 'Complexity Theory']),
      verified: true,
      isAvailable: false,
      ratingAvg: 5.0,
      reviewCount: 20,
      totalEarnings: 900,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      id: tutorIds.marco,
      location: 'Amsterdam, Netherlands',
      userId: userIds.marco,
      universityId: universityIds.hva,
      image: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Marco',
      bio: 'Friendly tutor making mathematics accessible to all',
      hourlyRate: 22,
      languages: JSON.stringify(['English', 'Italian']),
      courseTags: JSON.stringify(['Linear Algebra', 'Calculus', 'Statistics']),
      verified: true,
      isAvailable: true,
      ratingAvg: 4.6,
      reviewCount: 18,
      totalEarnings: 440,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      id: tutorIds.fatima,
      location: 'Amsterdam, Netherlands',
      userId: userIds.fatima,
      universityId: universityIds.uva,
      image: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Fatima',
      bio: 'Computer Science PhD student, expert in advanced algorithms',
      hourlyRate: 40,
      languages: JSON.stringify(['English', 'Chinese', 'Dutch']),
      courseTags: JSON.stringify(['Data Structures', 'Algorithms', 'Machine Learning']),
      verified: true,
      isAvailable: true,
      ratingAvg: 4.9,
      reviewCount: 11,
      totalEarnings: 440,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      id: tutorIds.chen,
      location: 'Amsterdam, Netherlands',
      userId: userIds.chen,
      universityId: universityIds.vu,
      image: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Chen',
      bio: 'Physics tutor with focus on conceptual understanding',
      hourlyRate: 28,
      languages: JSON.stringify(['English', 'Dutch', 'Portuguese']),
      courseTags: JSON.stringify(['Physics', 'Mechanics']),
      verified: true,
      isAvailable: true,
      ratingAvg: 4.4,
      reviewCount: 7,
      totalEarnings: 196,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
  ];

  await db.insert(tutors).values(sampleTutors);
  console.log('✅ Tutors seeded');
}

async function seedTutorCourses() {
  const sampleTutorCourses = [
    { id: uuidv4(), tutorId: tutorIds.emma, courseId: courseIds.linearAlgebra, experienceLevel: 'advanced', createdAt: new Date().toISOString() },
    { id: uuidv4(), tutorId: tutorIds.ahmed, courseId: courseIds.dataStructures, experienceLevel: 'advanced', createdAt: new Date().toISOString() },
    { id: uuidv4(), tutorId: tutorIds.sofia, courseId: courseIds.physics1, experienceLevel: 'advanced', createdAt: new Date().toISOString() },
    { id: uuidv4(), tutorId: tutorIds.lars, courseId: courseIds.linearAlgebra, experienceLevel: 'intermediate', createdAt: new Date().toISOString() },
    { id: uuidv4(), tutorId: tutorIds.lars, courseId: courseIds.physics1, experienceLevel: 'intermediate', createdAt: new Date().toISOString() },
    { id: uuidv4(), tutorId: tutorIds.priya, courseId: courseIds.dataStructures, experienceLevel: 'advanced', createdAt: new Date().toISOString() },
    { id: uuidv4(), tutorId: tutorIds.marco, courseId: courseIds.linearAlgebra, experienceLevel: 'advanced', createdAt: new Date().toISOString() },
    { id: uuidv4(), tutorId: tutorIds.fatima, courseId: courseIds.dataStructures, experienceLevel: 'advanced', createdAt: new Date().toISOString() },
    { id: uuidv4(), tutorId: tutorIds.chen, courseId: courseIds.physics1, experienceLevel: 'advanced', createdAt: new Date().toISOString() },
  ];

  await db.insert(tutorCourses).values(sampleTutorCourses);
  console.log('✅ Tutor Courses seeded');
}

async function seedAvailabilitySlots() {
  const sampleSlots = [
    {
      id: uuidv4(),
      tutorId: tutorIds.emma,
      dayOfWeek: 1,
      startTime: '09:00',
      endTime: '12:00',
      timezone: 'Europe/Amsterdam',
      isRecurring: true,
      isActive: true,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      id: uuidv4(),
      tutorId: tutorIds.emma,
      dayOfWeek: 3,
      startTime: '14:00',
      endTime: '17:00',
      timezone: 'Europe/Amsterdam',
      isRecurring: true,
      isActive: true,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      id: uuidv4(),
      tutorId: tutorIds.ahmed,
      dayOfWeek: 2,
      startTime: '14:00',
      endTime: '17:00',
      timezone: 'Europe/Amsterdam',
      isRecurring: true,
      isActive: true,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      id: uuidv4(),
      tutorId: tutorIds.ahmed,
      dayOfWeek: 5,
      startTime: '10:00',
      endTime: '13:00',
      timezone: 'Europe/Amsterdam',
      isRecurring: true,
      isActive: true,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      id: uuidv4(),
      tutorId: tutorIds.sofia,
      dayOfWeek: 1,
      startTime: '10:00',
      endTime: '13:00',
      timezone: 'Europe/Amsterdam',
      isRecurring: true,
      isActive: true,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      id: uuidv4(),
      tutorId: tutorIds.lars,
      dayOfWeek: 2,
      startTime: '16:00',
      endTime: '19:00',
      timezone: 'Europe/Amsterdam',
      isRecurring: true,
      isActive: true,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      id: uuidv4(),
      tutorId: tutorIds.priya,
      dayOfWeek: 3,
      startTime: '11:00',
      endTime: '14:00',
      timezone: 'Europe/Amsterdam',
      isRecurring: false,
      isActive: false,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      id: uuidv4(),
      tutorId: tutorIds.marco,
      dayOfWeek: 4,
      startTime: '09:00',
      endTime: '12:00',
      timezone: 'Europe/Amsterdam',
      isRecurring: true,
      isActive: true,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      id: uuidv4(),
      tutorId: tutorIds.fatima,
      dayOfWeek: 0,
      startTime: '15:00',
      endTime: '18:00',
      timezone: 'Europe/Amsterdam',
      isRecurring: true,
      isActive: true,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      id: uuidv4(),
      tutorId: tutorIds.chen,
      dayOfWeek: 5,
      startTime: '13:00',
      endTime: '16:00',
      timezone: 'Europe/Amsterdam',
      isRecurring: true,
      isActive: true,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
  ];

  await db.insert(availabilitySlots).values(sampleSlots);
  console.log('✅ Availability Slots seeded');
}

async function seedBookings() {
  const sampleBookings = [
    //{
    //  id: bookingIds.booking1,
    //  studentId: userIds.max,
    //  tutorId: tutorIds.emma,
    //  courseId: courseIds.linearAlgebra,
    //  sessionDate: '2024-02-15',
    //  startTime: '10:00',
    //  endTime: '11:00',
    //  duration: 60,
    //  hourlyRate: 25,
    //  totalAmount: 25,
    //  status: 'completed',
    //  createdAt: new Date().toISOString(),
    //  updatedAt: new Date().toISOString(),
    //},
    //{
    //  id: bookingIds.booking2,
    //  studentId: userIds.sarah,
    //  tutorId: tutorIds.ahmed,
    //  courseId: courseIds.dataStructures,
    //  sessionDate: '2024-02-16',
    //  startTime: '15:00',
    //  endTime: '16:00',
    //  duration: 60,
    //  hourlyRate: 30,
    //  totalAmount: 30,
    //  status: 'completed',
    //  createdAt: new Date().toISOString(),
    //  updatedAt: new Date().toISOString(),
    //},
    //{
    //  id: bookingIds.booking3,
    //  studentId: userIds.david,
    //  tutorId: tutorIds.sofia,
    //  courseId: courseIds.physics1,
    //  sessionDate: '2024-02-17',
    //  startTime: '11:00',
    //  endTime: '12:00',
    //  duration: 60,
    //  hourlyRate: 35,
    //  totalAmount: 35,
    //  status: 'completed',
    //  createdAt: new Date().toISOString(),
    //  updatedAt: new Date().toISOString(),
    //},
    //{
    //  id: bookingIds.booking4,
    //  studentId: userIds.max,
    //  tutorId: tutorIds.lars,
    //  courseId: courseIds.linearAlgebra,
    //  sessionDate: '2024-02-18',
    //  startTime: '17:00',
    //  endTime: '18:30',
    //  duration: 90,
    //  hourlyRate: 20,
    //  totalAmount: 30,
    //  status: 'completed',
    //  createdAt: new Date().toISOString(),
    //  updatedAt: new Date().toISOString(),
    //},
    //{
    //  id: bookingIds.booking5,
    //  studentId: userIds.sarah,
    //  tutorId: tutorIds.priya,
    //  courseId: courseIds.dataStructures,
    //  sessionDate: '2024-02-19',
    //  startTime: '12:00',
    //  endTime: '13:00',
    //  duration: 60,
    //  hourlyRate: 45,
    //  totalAmount: 45,
    //  status: 'completed',
    //  createdAt: new Date().toISOString(),
    //  updatedAt: new Date().toISOString(),
    //},
    //{
    //  id: bookingIds.booking6,
    //  studentId: userIds.lisa,
    //  tutorId: tutorIds.marco,
    //  courseId: courseIds.linearAlgebra,
    //  sessionDate: '2024-02-20',
    //  startTime: '10:00',
    //  endTime: '11:00',
    //  duration: 60,
    //  hourlyRate: 22,
    //  totalAmount: 22,
    //  status: 'completed',
    //  createdAt: new Date().toISOString(),
    //  updatedAt: new Date().toISOString(),
    //},
    //{
    //  id: bookingIds.booking7,
    //  studentId: userIds.david,
    //  tutorId: tutorIds.fatima,
    //  courseId: courseIds.dataStructures,
    //  sessionDate: '2024-02-21',
    //  startTime: '16:00',
    //  endTime: '17:00',
    //  duration: 60,
    //  hourlyRate: 40,
    //  totalAmount: 40,
    //  status: 'completed',
    //  createdAt: new Date().toISOString(),
    //  updatedAt: new Date().toISOString(),
    //},
    //{
    //  id: bookingIds.booking8,
    //  studentId: userIds.lisa,
    //  tutorId: tutorIds.chen,
    //  courseId: courseIds.physics1,
    //  sessionDate: '2024-02-22',
    //  startTime: '14:00',
    //  endTime: '15:00',
    //  duration: 60,
    //  hourlyRate: 28,
    //  totalAmount: 28,
    //  status: 'completed',
    //  createdAt: new Date().toISOString(),
    //  updatedAt: new Date().toISOString(),
    //},
    {
      id: bookingIds.booking9,
      studentId: userIds.student,
      tutorId: tutorIds.chat,
      courseId: courseIds.linearAlgebra,
      sessionDate: '2025-12-20',
      startTime: '10:00',
      endTime: '11:00',
      duration: 60,
      hourlyRate: 50,
      totalAmount: 50,
      status: 'completed',
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
  ];

  await db.insert(bookings).values(sampleBookings);
  console.log('✅ Bookings seeded');
}

async function seedBookingEvents() {
  const sampleEvents = [
    { id: uuidv4(), bookingId: bookingIds.booking1, eventType: 'completed', triggeredBy: userIds.emma, createdAt: new Date().toISOString() },
    { id: uuidv4(), bookingId: bookingIds.booking2, eventType: 'completed', triggeredBy: userIds.ahmed, createdAt: new Date().toISOString() },
    { id: uuidv4(), bookingId: bookingIds.booking3, eventType: 'completed', triggeredBy: userIds.sofia, createdAt: new Date().toISOString() },
    { id: uuidv4(), bookingId: bookingIds.booking4, eventType: 'completed', triggeredBy: userIds.lars, createdAt: new Date().toISOString() },
    { id: uuidv4(), bookingId: bookingIds.booking5, eventType: 'completed', triggeredBy: userIds.priya, createdAt: new Date().toISOString() },
    { id: uuidv4(), bookingId: bookingIds.booking6, eventType: 'completed', triggeredBy: userIds.marco, createdAt: new Date().toISOString() },
    { id: uuidv4(), bookingId: bookingIds.booking7, eventType: 'completed', triggeredBy: userIds.fatima, createdAt: new Date().toISOString() },
    { id: uuidv4(), bookingId: bookingIds.booking8, eventType: 'completed', triggeredBy: userIds.chen, createdAt: new Date().toISOString() },
  ];

  await db.insert(bookingEvents).values(sampleEvents);
  console.log('✅ Booking Events seeded');
}

async function seedPayouts() {
  const samplePayouts = [
    {
      id: uuidv4(),
      tutorId: tutorIds.emma,
      bookingId: bookingIds.booking1,
      amount: 25,
      platformFee: 2.5,
      netAmount: 22.5,
      status: 'completed',
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      id: uuidv4(),
      tutorId: tutorIds.ahmed,
      bookingId: bookingIds.booking2,
      amount: 30,
      platformFee: 3,
      netAmount: 27,
      status: 'completed',
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      id: uuidv4(),
      tutorId: tutorIds.sofia,
      bookingId: bookingIds.booking3,
      amount: 35,
      platformFee: 3.5,
      netAmount: 31.5,
      status: 'completed',
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      id: uuidv4(),
      tutorId: tutorIds.lars,
      bookingId: bookingIds.booking4,
      amount: 30,
      platformFee: 3,
      netAmount: 27,
      status: 'completed',
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      id: uuidv4(),
      tutorId: tutorIds.priya,
      bookingId: bookingIds.booking5,
      amount: 45,
      platformFee: 4.5,
      netAmount: 40.5,
      status: 'completed',
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      id: uuidv4(),
      tutorId: tutorIds.marco,
      bookingId: bookingIds.booking6,
      amount: 22,
      platformFee: 2.2,
      netAmount: 19.8,
      status: 'completed',
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      id: uuidv4(),
      tutorId: tutorIds.fatima,
      bookingId: bookingIds.booking7,
      amount: 40,
      platformFee: 4,
      netAmount: 36,
      status: 'completed',
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      id: uuidv4(),
      tutorId: tutorIds.chen,
      bookingId: bookingIds.booking8,
      amount: 28,
      platformFee: 2.8,
      netAmount: 25.2,
      status: 'completed',
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
  ];

  await db.insert(payouts).values(samplePayouts);
  console.log('✅ Payouts seeded');
}

async function seedReviews() {
  const sampleReviews = [
    {
      id: uuidv4(),
      bookingId: bookingIds.booking1,
      studentId: userIds.max,
      tutorId: tutorIds.emma,
      rating: 5,
      comment: 'Excellent tutor, very helpful!',
      isPublic: true,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      id: uuidv4(),
      bookingId: bookingIds.booking2,
      studentId: userIds.sarah,
      tutorId: tutorIds.ahmed,
      rating: 5,
      comment: 'Great session, learned a lot!',
      isPublic: true,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      id: uuidv4(),
      bookingId: bookingIds.booking3,
      studentId: userIds.david,
      tutorId: tutorIds.sofia,
      rating: 5,
      comment: 'Fantastic physics explanations, highly recommend!',
      isPublic: true,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      id: uuidv4(),
      bookingId: bookingIds.booking4,
      studentId: userIds.max,
      tutorId: tutorIds.lars,
      rating: 4,
      comment: 'Good tutor, very patient and understanding',
      isPublic: true,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      id: uuidv4(),
      bookingId: bookingIds.booking5,
      studentId: userIds.sarah,
      tutorId: tutorIds.priya,
      rating: 5,
      comment: 'Outstanding knowledge in algorithms. Best tutor ever!',
      isPublic: true,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      id: uuidv4(),
      bookingId: bookingIds.booking6,
      studentId: userIds.lisa,
      tutorId: tutorIds.marco,
      rating: 5,
      comment: 'Made mathematics easy and fun!',
      isPublic: true,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      id: uuidv4(),
      bookingId: bookingIds.booking7,
      studentId: userIds.david,
      tutorId: tutorIds.fatima,
      rating: 5,
      comment: 'Amazing CS expert, very clear explanations',
      isPublic: true,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      id: uuidv4(),
      bookingId: bookingIds.booking8,
      studentId: userIds.lisa,
      tutorId: tutorIds.chen,
      rating: 4,
      comment: 'Good physics tutor, very knowledgeable',
      isPublic: true,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
  ];

  await db.insert(reviews).values(sampleReviews);
  console.log('✅ Reviews seeded');
}

async function seedConversations() {
  const now = new Date('2024-03-01T10:30:00').toISOString();
  const sampleConversations = [
    // Max (student) ↔ Emma (tutor)
    {
      id: conversationIds.maxEmma,
      user1Id: userIds.max,
      user2Id: userIds.emma,
      lastMessageAt: new Date('2024-03-10T18:00:00').toISOString(),
      lastMessageContent: "Hi Max! Just checking if you're ready for our session tomorrow.",
      unreadCount: 1,
      createdAt: new Date('2024-03-01T10:30:00').toISOString(),
      updatedAt: new Date('2024-03-10T18:00:00').toISOString(),
    },
    // Sarah (student) ↔ Ahmed (tutor)
    {
      id: conversationIds.sarahAhmed,
      user1Id: userIds.sarah,
      user2Id: userIds.ahmed,
      lastMessageAt: new Date('2024-03-02T10:00:00').toISOString(),
      lastMessageContent: "Great! I've booked the session. Bring your code and we'll go through it together.",
      unreadCount: 0,
      createdAt: new Date('2024-03-02T09:00:00').toISOString(),
      updatedAt: new Date('2024-03-02T10:00:00').toISOString(),
    },
    // David (student) ↔ Sofia (tutor)
    {
      id: conversationIds.davidSofia,
      user1Id: userIds.david,
      user2Id: userIds.sofia,
      lastMessageAt: new Date('2024-03-03T15:15:00').toISOString(),
      lastMessageContent: "Perfect timing! Session booked for Thursday at 3 PM. I'll prepare some practice problems.",
      unreadCount: 0,
      createdAt: new Date('2024-03-03T14:00:00').toISOString(),
      updatedAt: new Date('2024-03-03T15:15:00').toISOString(),
    },
    // Lisa (student) ↔ Lars (tutor)
    {
      id: conversationIds.lisaLars,
      user1Id: userIds.lisa,
      user2Id: userIds.lars,
      lastMessageAt: new Date('2024-03-04T16:45:00').toISOString(),
      lastMessageContent: 'Those are my specialty! Session booked. Bring your notes and past exams.',
      unreadCount: 0,
      createdAt: new Date('2024-03-04T16:00:00').toISOString(),
      updatedAt: new Date('2024-03-04T16:45:00').toISOString(),
    },
    // Max (student) ↔ Priya (tutor) - New conversation with unread
    {
      id: conversationIds.maxPriya,
      user1Id: userIds.max,
      user2Id: userIds.priya,
      lastMessageAt: new Date('2024-03-10T09:00:00').toISOString(),
      lastMessageContent: 'Hi Priya! I saw you teach Data Structures. Are you available next week?',
      unreadCount: 1,
      createdAt: new Date('2024-03-10T09:00:00').toISOString(),
      updatedAt: new Date('2024-03-10T09:00:00').toISOString(),
    },
    // Sarah (student) ↔ Marco (tutor) - New conversation with unread
    {
      id: conversationIds.sarahMarco,
      user1Id: userIds.sarah,
      user2Id: userIds.marco,
      lastMessageAt: new Date('2024-03-10T10:30:00').toISOString(),
      lastMessageContent: 'Hello Marco, do you have experience with advanced algorithms?',
      unreadCount: 1,
      createdAt: new Date('2024-03-10T10:30:00').toISOString(),
      updatedAt: new Date('2024-03-10T10:30:00').toISOString(),
    },
    // David (student) ↔ Fatima (tutor) - New conversation with unread
    {
      id: conversationIds.davidFatima,
      user1Id: userIds.david,
      user2Id: userIds.fatima,
      lastMessageAt: new Date('2024-03-10T15:45:00').toISOString(),
      lastMessageContent: 'Hi Fatima, I need help with Physics homework due tomorrow.',
      unreadCount: 1,
      createdAt: new Date('2024-03-10T15:45:00').toISOString(),
      updatedAt: new Date('2024-03-10T15:45:00').toISOString(),
    },
  ];

  await db.insert(conversations).values(sampleConversations);
  console.log('✅ Conversations seeded');
}

async function seedMessages() {
  const sampleMessages = [
    // Conversation between Max (student) and Emma (tutor)
    {
      id: uuidv4(),
      conversationId: conversationIds.maxEmma,
      senderId: userIds.max,
      content: 'Hi Emma! I saw your profile and would like some help with Linear Algebra. Are you available this week?',
      messageType: 'text',
      bookingId: null,
      isRead: true,
      createdAt: new Date('2024-03-01T10:30:00').toISOString(),
      updatedAt: new Date('2024-03-01T10:30:00').toISOString(),
    },
    {
      id: uuidv4(),
      conversationId: conversationIds.maxEmma,
      senderId: userIds.emma,
      content: 'Hi Max! Yes, I can help with Linear Algebra. I have availability on Wednesday and Friday afternoons. What topics are you struggling with?',
      messageType: 'text',
      bookingId: null,
      isRead: true,
      createdAt: new Date('2024-03-01T11:15:00').toISOString(),
      updatedAt: new Date('2024-03-01T11:15:00').toISOString(),
    },
    {
      id: uuidv4(),
      conversationId: conversationIds.maxEmma,
      senderId: userIds.max,
      content: 'Great! I need help with matrix operations and eigenvalues. Wednesday at 2 PM works for me.',
      messageType: 'text',
      bookingId: null,
      isRead: true,
      createdAt: new Date('2024-03-01T11:45:00').toISOString(),
      updatedAt: new Date('2024-03-01T11:45:00').toISOString(),
    },
    {
      id: uuidv4(),
      conversationId: conversationIds.maxEmma,
      senderId: userIds.emma,
      content: 'Perfect! I\'ve created a booking for Wednesday at 2 PM. See you then!',
      messageType: 'text',
      bookingId: bookingIds.booking1,
      isRead: true,
      createdAt: new Date('2024-03-01T12:00:00').toISOString(),
      updatedAt: new Date('2024-03-01T12:00:00').toISOString(),
    },
    {
      id: uuidv4(),
      conversationId: conversationIds.maxEmma,
      senderId: userIds.max,
      content: 'Thanks Emma! Looking forward to it.',
      messageType: 'text',
      bookingId: bookingIds.booking1,
      isRead: true,
      createdAt: new Date('2024-03-01T12:10:00').toISOString(),
      updatedAt: new Date('2024-03-01T12:10:00').toISOString(),
    },

    // Conversation between Sarah (student) and Ahmed (tutor)
    {
      id: uuidv4(),
      conversationId: conversationIds.sarahAhmed,
      senderId: userIds.sarah,
      content: 'Hi Ahmed, I need urgent help with my Data Structures assignment. Can you help me today?',
      messageType: 'text',
      bookingId: null,
      isRead: true,
      createdAt: new Date('2024-03-02T09:00:00').toISOString(),
      updatedAt: new Date('2024-03-02T09:00:00').toISOString(),
    },
    {
      id: uuidv4(),
      conversationId: conversationIds.sarahAhmed,
      senderId: userIds.ahmed,
      content: 'Hi Sarah! I can help you today at 4 PM. What specific topics are you working on?',
      messageType: 'text',
      bookingId: null,
      isRead: true,
      createdAt: new Date('2024-03-02T09:30:00').toISOString(),
      updatedAt: new Date('2024-03-02T09:30:00').toISOString(),
    },
    {
      id: uuidv4(),
      conversationId: conversationIds.sarahAhmed,
      senderId: userIds.sarah,
      content: 'Binary search trees and graph traversal algorithms. 4 PM works perfectly!',
      messageType: 'text',
      bookingId: null,
      isRead: true,
      createdAt: new Date('2024-03-02T09:45:00').toISOString(),
      updatedAt: new Date('2024-03-02T09:45:00').toISOString(),
    },
    {
      id: uuidv4(),
      conversationId: conversationIds.sarahAhmed,
      senderId: userIds.ahmed,
      content: 'Great! I\'ve booked the session. Bring your code and we\'ll go through it together.',
      messageType: 'text',
      bookingId: bookingIds.booking2,
      isRead: true,
      createdAt: new Date('2024-03-02T10:00:00').toISOString(),
      updatedAt: new Date('2024-03-02T10:00:00').toISOString(),
    },

    // Conversation between David (student) and Sofia (tutor)
    {
      id: uuidv4(),
      conversationId: conversationIds.davidSofia,
      senderId: userIds.david,
      content: 'Hello Sofia, I\'m struggling with Physics concepts. Do you have time this week?',
      messageType: 'text',
      bookingId: null,
      isRead: true,
      createdAt: new Date('2024-03-03T14:00:00').toISOString(),
      updatedAt: new Date('2024-03-03T14:00:00').toISOString(),
    },
    {
      id: uuidv4(),
      conversationId: conversationIds.davidSofia,
      senderId: userIds.sofia,
      content: 'Hi David! Yes, I can help. I have slots on Thursday and Friday. Which topics do you need help with?',
      messageType: 'text',
      bookingId: null,
      isRead: true,
      createdAt: new Date('2024-03-03T14:30:00').toISOString(),
      updatedAt: new Date('2024-03-03T14:30:00').toISOString(),
    },
    {
      id: uuidv4(),
      conversationId: conversationIds.davidSofia,
      senderId: userIds.david,
      content: 'Mainly kinematics and Newton\'s laws. Thursday at 3 PM would be ideal.',
      messageType: 'text',
      bookingId: null,
      isRead: true,
      createdAt: new Date('2024-03-03T15:00:00').toISOString(),
      updatedAt: new Date('2024-03-03T15:00:00').toISOString(),
    },
    {
      id: uuidv4(),
      conversationId: conversationIds.davidSofia,
      senderId: userIds.sofia,
      content: 'Perfect timing! Session booked for Thursday at 3 PM. I\'ll prepare some practice problems.',
      messageType: 'text',
      bookingId: bookingIds.booking3,
      isRead: true,
      createdAt: new Date('2024-03-03T15:15:00').toISOString(),
      updatedAt: new Date('2024-03-03T15:15:00').toISOString(),
    },

    // Conversation between Lisa (student) and Lars (tutor)
    {
      id: uuidv4(),
      conversationId: conversationIds.lisaLars,
      senderId: userIds.lisa,
      content: 'Hey Lars, can you help me prepare for my Linear Algebra exam next week?',
      messageType: 'text',
      bookingId: null,
      isRead: true,
      createdAt: new Date('2024-03-04T16:00:00').toISOString(),
      updatedAt: new Date('2024-03-04T16:00:00').toISOString(),
    },
    {
      id: uuidv4(),
      conversationId: conversationIds.lisaLars,
      senderId: userIds.lars,
      content: 'Hi Lisa! Of course. I recommend 2-hour sessions for exam prep. How about tomorrow at 1 PM?',
      messageType: 'text',
      bookingId: null,
      isRead: true,
      createdAt: new Date('2024-03-04T16:20:00').toISOString(),
      updatedAt: new Date('2024-03-04T16:20:00').toISOString(),
    },
    {
      id: uuidv4(),
      conversationId: conversationIds.lisaLars,
      senderId: userIds.lisa,
      content: 'That sounds great! I really need to nail vector spaces and linear transformations.',
      messageType: 'text',
      bookingId: null,
      isRead: true,
      createdAt: new Date('2024-03-04T16:30:00').toISOString(),
      updatedAt: new Date('2024-03-04T16:30:00').toISOString(),
    },
    {
      id: uuidv4(),
      conversationId: conversationIds.lisaLars,
      senderId: userIds.lars,
      content: 'Those are my specialty! Session booked. Bring your notes and past exams.',
      messageType: 'text',
      bookingId: bookingIds.booking4,
      isRead: true,
      createdAt: new Date('2024-03-04T16:45:00').toISOString(),
      updatedAt: new Date('2024-03-04T16:45:00').toISOString(),
    },

    // Recent unread messages
    {
      id: uuidv4(),
      conversationId: conversationIds.maxPriya,
      senderId: userIds.max,
      content: 'Hi Priya! I saw you teach Data Structures. Are you available next week?',
      messageType: 'text',
      bookingId: null,
      isRead: false,
      createdAt: new Date('2024-03-10T09:00:00').toISOString(),
      updatedAt: new Date('2024-03-10T09:00:00').toISOString(),
    },
    {
      id: uuidv4(),
      conversationId: conversationIds.sarahMarco,
      senderId: userIds.sarah,
      content: 'Hello Marco, do you have experience with advanced algorithms? I need help with dynamic programming.',
      messageType: 'text',
      bookingId: null,
      isRead: false,
      createdAt: new Date('2024-03-10T10:30:00').toISOString(),
      updatedAt: new Date('2024-03-10T10:30:00').toISOString(),
    },
    {
      id: uuidv4(),
      conversationId: conversationIds.davidFatima,
      senderId: userIds.david,
      content: 'Hi Fatima, I need help with Physics homework due tomorrow. Can you squeeze me in?',
      messageType: 'text',
      bookingId: null,
      isRead: false,
      createdAt: new Date('2024-03-10T15:45:00').toISOString(),
      updatedAt: new Date('2024-03-10T15:45:00').toISOString(),
    },
    {
      id: uuidv4(),
      conversationId: conversationIds.maxEmma,
      senderId: userIds.emma,
      content: 'Hi Max! Just checking if you\'re ready for our session tomorrow. Let me know if you have any questions beforehand.',
      messageType: 'text',
      bookingId: bookingIds.booking5,
      isRead: false,
      createdAt: new Date('2024-03-10T18:00:00').toISOString(),
      updatedAt: new Date('2024-03-10T18:00:00').toISOString(),
    },
  ];

  await db.insert(messages).values(sampleMessages);
  console.log('✅ Messages seeded');
}

async function main() {
  // Run this script: npx tsx src/db/seeds/seed.ts
  try {
    console.log('🌱 Starting database seeding...\n');
    
    //await seedUniversities();

    //await seedCourses();
    //await seeduser();
    //await seedTutors();
    //await seedTutorCourses();
    //await seedAvailabilitySlots();
    await seedBookings();
    //await seedBookingEvents();
    //await seedPayouts();
    //await seedReviews();
    //await seedConversations();
    //await seedMessages();

    console.log('\n✅ All seeders completed successfully!');
    process.exit(0);
  } catch (error) {
    console.error('❌ Seeding failed:', error);
    process.exit(1);
  }
}

main();
